package com.thomsonreuters.entities;

import lombok.Data;


import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;

@Data
@Entity
@Table(name = "EX_STG_EXECUTIONS")
public class StgExecutions implements Serializable {

    /**
     * UID generated by Intellij
     */
    private static final long serialVersionUID = -4575582287641037247L;

    /**
     * database ID of the staging executions
     */
    @Id
    @Column(name = "STAGING_EXECUTIONS_ID")
    private Long stagingExecutionsId;

    /**
     * database ID of the batch
     */
    @Column(name = "BATCH_ID")
    private Long batchId;

    /**
     * database ID of the extract
     */
    @Column(name = "EXTRACT_ID")
    private Long extractId;

    /**
     * start day/time of the staging run for the extract
     */
    @Column(name = "START_DATE")
    private LocalDateTime startDate;

    /**
     * end day/time of the staging run for the extract
     */
    @Column(name = "END_DATE")
    private LocalDateTime endDate;

    /**
     * the status of the staging run for a extract
     */
    @Column(name = "STATUS")
    private String status;

    /**
     * message pertaining to this run for the extract
     */
    @Column(name = "MESSAGE")
    private String message;

    /**
     * The content version for the staging execution run
     */
    @Column(name = "CONTENT_VERSION")
    private Long contentVersion;

    /**
     * the process id of the staging process, used to identify which staging process generate this execution record
     */
    @Column(name = "PROCESS_ID")
    private String processId;

    /**
     * date at which the extract was synchronized in the database
     */
    @Column(name = "SYNCHRONIZATION_TIMESTAMP")
    private LocalDateTime synchronizationTimestamp;

}
